name: docker-restic-config

services:
  restic:
    image: restic/restic:0.18.1
    container_name: restic
    environment:
      - TZ=Europe/Berlin
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RESTIC_PAPERLESS_REPOSITORY=${RESTIC_PAPERLESS_REPOSITORY:-sftp:tiffy:/data/zeus/restic/paperless}
      - RESTIC_KEEP_DAILY=${RESTIC_KEEP_DAILY}
      - RESTIC_KEEP_WEEKLY=${RESTIC_KEEP_WEEKLY}
      - RESTIC_KEEP_MONTHLY=${RESTIC_KEEP_MONTHLY}
    volumes:
      - ${RESTIC_REPOSITORY_DIR:-/opt/docker/restic/repository}:/repository
      - ${RESTIC_CACHE_DIR}:/cache
      - ${RESTIC_RESTORE_DIR}:/restore
      - ${RESTIC_SSH_DIR:-/opt/docker/duplicati/config/.ssh}:/root/.ssh:ro
      - ${BACKUP_SOURCE_ZEUS}:/source/zeus:ro
      - ${BACKUP_SOURCE_ECODMS}:/source/ecodms:ro
      - ${BACKUP_SOURCE_PAPERLESS}:/source/paperless-ngx:ro
      - ${BACKUP_SOURCE_PAPERLESS_DATA}:/source/paperless-data:ro
      - ${BACKUP_SOURCE_PAPERLESS_MEDIA}:/source/paperless-media:ro
      - ${BACKUP_SOURCE_ETC}:/source/etc:ro
      - ${BACKUP_SOURCE_FHEM}:/source/fhem:ro
      - ${BACKUP_SOURCE_WORDPRESS}:/source/wordpress:ro
      - ${BACKUP_SOURCE_PICTURES}:/source/pictures:ro
      - ${BACKUP_SOURCE_BITWARDEN}:/source/bitwarden:ro
      - ${BACKUP_SOURCE_Z2M}:/source/z2m:ro
      - ${BACKUP_SOURCE_N8N}:/source/n8n:ro
      - ${BACKUP_SOURCE_PORTAINER}:/source/portainer:ro
      - ./scripts:/scripts:ro
    configs:
      - source: restic_ssh_config
        target: /etc/ssh/ssh_config.d/tiffy.conf
        mode: 0400
      - source: restic_known_hosts
        target: /etc/restic/known_hosts
        mode: 0400
    extra_hosts:
      - "tiffy:192.168.125.4"
    networks:
      - default
      - backend_net
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.12.88/30
          gateway: 172.27.12.89
  backend_net:
    external: true
    name: network_backend_net

configs:
  restic_ssh_config:
    content: |
      Host tiffy
        HostName tiffy
        Port 2222
        User sbackupftp
        IdentityFile /root/.ssh/id.key
        IdentitiesOnly yes
        UserKnownHostsFile /etc/restic/known_hosts
        StrictHostKeyChecking yes
  restic_known_hosts:
    content: |
      [tiffy]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgnB1dfmEWCft9JXYpJo7Pxa3/fy/RpV1HbsDfSsD+H
